export default [
  {
    nickName: "拂山",
    name: "贾松",
    workId: "74803",
    title: "EHR-前端开发-财务线",
    imageUrl: "//gw.alicdn.com/tps/i4/TB1PqqyHXXXXXarXVXXLDO01XXX-319-319.jpg"
  }, {
    nickName: "九神",
    name: "邵寒超",
    workId: "67732",
    title: "EHR-前端开发",
    imageUrl: "//gw.alicdn.com/tps/TB1XTEAJFXXXXXjXVXXXXXXXXXX-2448-2448.jpg"
  },
  {
    nickName: "茶山",
    name: "张烨",
    workId: "81093",
    title: "行政&协同-UED",
    imageUrl: "//gw.alicdn.com/tps/TB1Qk3YJpXXXXXwXVXXXXXXXXXX-355-358.jpg"
  }, {
    nickName: "羞花",
    name: "黄琼",
    workId: "28701",
    title: "行政&协同-UED",
    imageUrl: "//gw.alicdn.com/tps/TB1G1oQJpXXXXX2aXXXXXXXXXXX-1836-1836.jpg"
  }, {
    nickName: "莫筝",
    name: "苏文苑",
    workId: "99982",
    title: "CTO-技术发展部",
    imageUrl: "//gw.alicdn.com/tps/TB1qru1JVXXXXaDXVXXXXXXXXXX-1231-997.png"
  }, {
    nickName: "多月",
    name: "叶雅巧",
    workId: "72953",
    title: "行政&协同-UED",
    imageUrl: "//gw.alicdn.com/tps/TB1C6g4JpXXXXX3XFXXXXXXXXXX-640-640.jpg"
  }, {
    nickName: "太奈",
    name: "徐飞",
    workId: "16949",
    title: "核心业务-技术二部-UED&策划运营",
    imageUrl: "//gw.alicdn.com/tps/TB1fKs6JpXXXXcSXpXXXXXXXXXX-1280-1280.jpg"
  }, {
    nickName: "钰馨",
    name: "郝晓敏",
    workId: "86960",
    title: "核心业务-技术二部-UED&策划运营",
    imageUrl: "//gw.alicdn.com/tps/TB1_i4aJFXXXXXJXpXXXXXXXXXX-389-389.jpg"
  }, {
    nickName: "仓舒",
    name: "曹柯",
    workId: "67955",
    title: "EHR-前端开发-基础架构",
    imageUrl: "//gw.alicdn.com/tps/i3/TB1CMOEHXXXXXXYXpXXeWY9VXXX-385-385.png"
  }, {
    nickName: "芠鸯",
    name: "边晓阳",
    workId: "87029",
    title: "核心业务-技术二部-UED&策划运营",
    imageUrl: "//gw.alicdn.com/tps/TB1rGQ1JpXXXXb.XFXXXXXXXXXX-370-376.jpg"
  }, {
    nickName: "光弘",
    name: "王思佳",
    workId: "87181",
    title: "EHR-前端开发-基础架构",
    imageUrl: "//gw.alicdn.com/tps/TB1MUg.JpXXXXbHXXXXXXXXXXXX-2340-2340.jpg"
  }, {
    nickName: "涵宇",
    name: "沈滨洋",
    workId: "31174",
    title: "EHR-前端开发-EHR线",
    imageUrl: "//gw.alicdn.com/tps/i1/TB1xquGHXXXXXb3XXXXeRjwSVXX-2736-2834.jpg"
  }, {
    nickName: "张顺",
    name: "康宁波",
    workId: "24668",
    title: "EHR-前端开发",
    imageUrl: "//gw.alicdn.com/tps/i1/TB1ZeiyHXXXXXXDXFXXupdCSXXX-2760-2760.jpg"
  }, {
    nickName: "一篙",
    name: "刘敏杰",
    workId: "80385",
    title: "EHR-前端开发-财务线",
    imageUrl: "//gw.alicdn.com/tps/TB1NxQWJpXXXXcqXFXXXXXXXXXX-2736-3648.jpg"
  }, {
    nickName: "兰弼",
    name: "董瑞阳",
    workId: "65587",
    title: "EHR-前端开发",
    imageUrl: "//gw.alicdn.com/tps/i3/TB1RwSxHXXXXXa6XVXXFSNq0VXX-640-663.jpg"
  }, {
    nickName: "康为",
    name: "晏兵兵",
    workId: "85377",
    title: "EHR-前端开发-财务线",
    imageUrl: "//gw.alicdn.com/tps/TB1BM7PJpXXXXXraXXXXXXXXXXX-540-540.jpg"
  }, {
    nickName: "金鸿",
    name: "张金红",
    workId: "72053",
    title: "EHR-前端开发-EHR线",
    imageUrl: "//gw.alicdn.com/tps/i1/TB13N9GHXXXXXXdXXXXBV9TYFXX-952-952.jpg"
  }, {
    nickName: "吴琼",
    name: "吴琼",
    workId: "55943",
    title: "EHR-前端开发-EHR线",
    imageUrl: "//gw.alicdn.com/tps/i4/TB1NNeEHXXXXXXlXVXXx2rSIVXX-600-600.jpg"
  }
];
